name: IAS Scan
on:
  push:
    branches: [ master ]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - id: my-scan
        uses: nmorrissey-r7/insightappsec-scan-github-actions@v1.3.2
        with:
          region: us
          api-key: ${{ secrets.IAS_API_KEY }}
          scan-config-id: '5eed6451-c8ca-4faa-a4bf-c3e3b8a0e7ea'
          scan-timeout-mins: 1
          vuln-query: "vulnerability.severity = 'HIGH'"
      - name: Upload findings
        if: always()
        run: echo "${{ steps.my-scan.outputs.scan-findings }}"
  deploy:
    runs-on: ubuntu-latest
    needs: [scan]
    steps:
      - name: Deploy artifact
        run: echo "Deploying..."
